boostcampwm-2022/web14-interface

frontend/src/components/IntervieweeVideo/IntervieweeVideo.tsx, frontend/src/pages/Feedback.tsx, frontend/src/store/feedbackStore.ts
- close issue #15 
- isFbClicked 로직을 추가해 특정 상황에서만 currentTime이 변경되도록 했습니다.
- 오타 수정
- `12-fe-feedbackarea-컴포넌트-구현` 브랜치를 base로 해당 브랜치 생성했습니다.
- `12-fe-feedbackarea-컴포넌트-구현` -> `dev` merge 이전에 이 PR을 먼저 merge 해주세요.
=> currenttime의존 useeffect 로직 변경

frontend/src/pages/Feedback.tsx
=> video feedbackarea 동기화

backend/src/auth/auth.module.ts, backend/src/auth/controller/auth.controller.ts, backend/src/auth/service/auth.service.ts, backend/src/constant/auth.constant.ts, backend/src/constant/http.constant.ts
- close issue #26
- merge conflict를 실제 코드를 로컬에서 안보고 github상에서 하니까 pull 받아보니 오류가 있어서 수정
- HTTP관련 status를 constant뺀 것을 enum으로 처리하면서 관련된 JWT 변수가 많아서 그것도 enum처리
=> BE merge conflict 이슈 및 간단한 리팩토링

frontend/src/components/@shared/TextArea/TextArea.tsx, frontend/src/components/FeedbackArea/FeedbackArea.tsx
- close #17 
- @shared 컴포넌트에 TextArea 추가
- FeedbackArea에 FATextArea를 @shared/TextArea를 사용하도록 변경
- FATextArea가 input 상태를 가지도록 변경
- Shift + Enter 시, 줄바꿈, Enter 시 onInsertFeedback 함수가 실행되는 로직 추가
- Shift + Enter 시, 줄바꿈, Enter 시 onInsertFeedback 함수가 실행되는 로직 추가
이 기능을 하는 함수의 이름을 찾습니다. HELP
=> FE - FATextArea 추출

frontend/src/pages/Interviewer/Interviewer.tsx
page 디렉터리 구조 변경으로 socket service import 경로를 최신화
=> hotfix: (fe) - socket service 경로 최신화

frontend/public/index.html, frontend/src/components/EditableFeedbackBox/EditableFeedbackBox.style.ts, frontend/src/components/EditableFeedbackBox/EditableFeedbackBox.tsx, frontend/src/components/FeedbackArea/FeedbackArea.style.ts, frontend/src/components/FeedbackArea/FeedbackArea.tsx, frontend/src/components/FeedbackForm/FeedbackForm.style.ts, frontend/src/components/FeedbackForm/FeedbackForm.tsx, frontend/src/components/IntervieweeVideo/IntervieweeVideo.tsx, frontend/src/customType/feedback.d.ts, frontend/src/hooks/useCrudFeedback.ts, frontend/src/pages/Feedback/Feddback.style.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/store/auth.atom.ts, frontend/src/store/currentVideoTime.atom.ts, frontend/src/store/feedback.atom.ts, frontend/src/store/focusIndex.atom.ts, frontend/src/styles/theme.ts
- close issue #60 
- #57 피드백 사항 모두 반영했습니다.
=> 피드백 페이지 버그 수정 및 리팩터링

frontend/src/pages/Interviewer/Interviewer.tsx
Interviewer 페이지에 webRTC를 사용할 수 있도록 이식하였습니다.
- close issue #64 
없음.
아마 차후에 stream selector가 MediaStream[]가 아니라 uuid, Mediastream을 포함하는 객체의 배열로 바뀔 것 같습니다.
이부분은 Lobby에서 API를 붙여야 할 수 있을 것 같아서 일단은 구현된 대로 MediaStream 으로 이식해놨습니다.
=> Interviewer 페이지에 webRTC 이식

frontend/src/pages/Interviewee/Interviewee.tsx
Interviewee 페이지에 webRTC를 이식합니다.
- close issue #65 
없음
아마 차후에 stream selector가 MediaStream[]가 아니라 uuid, Mediastream을 포함하는 객체의 배열로 바뀔 것 같습니다.
이부분은 Lobby에서 API를 붙여야 할 수 있을 것 같아서 일단은 구현된 대로 MediaStream 으로 이식해놨습니다.
=> Interviewee 페이지에 webRTC 이식

frontend/.storybook/main.js
Storybook emotion css props 미인식 버그 수정
- close issue #78 
없음
없음
=> Storybook emotion css props 미인식 버그 수정

frontend/.gitignore, frontend/package.json, frontend/src/App.tsx, frontend/src/pages/Landing/Landing.tsx, frontend/src/pages/Login/Login.tsx, frontend/src/pages/NotFound/NotFound.tsx, frontend/src/pages/Waitting/Waitting.tsx, frontend/src/routes/PrivateRoutes.tsx, frontend/src/routes/PublicRoutes.tsx, frontend/src/routes/RootRoutes.tsx, frontend/src/service/socket.ts, frontend/src/setupProxy.js, frontend/src/store/authState.ts
- private / public 라우팅 분기 로직 리팩토링
- fe devserver proxy 설정
- close issue #72
=> protected routing 로직변경

frontend/src/components/@shared/VideoGrid/VideoGrid.style.ts, frontend/src/components/@shared/VideoGrid/VideoGrid.tsx
로비에 사용될 비디오 그리드 제작
- close issue #62 
[VideoGrid.tsx](https://github.com/boostcampwm-2022/web14-interface/compare/62-%EB%B9%84%EB%94%94%EC%98%A4-%EA%B7%B8%EB%A6%AC%EB%93%9C-%EB%A7%8C%EB%93%A4%EA%B8%B0?expand=1#diff-2148e485dee556b5c3f636af6fca4398f7146d45bb7a0c0c4651079ab498e7be)
[VideoGrid.style.ts](https://github.com/boostcampwm-2022/web14-interface/pull/77/files#diff-138f1efce705d7872644a6911da340b6e72f3a6937b0277a78471c9a2aca0427)
없음
=> VideoGrid 제작

backend/socket/src/room/repository/inmemory-room.repository.ts, backend/socket/src/room/service/connection/connection.service.ts, backend/socket/src/room/service/interview/interview.service.ts, frontend/src/hooks/useSafeNavigate.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/pages/Interviewee/Interviewee.tsx, frontend/src/pages/Interviewer/Interviewer.tsx, frontend/src/pages/Landing/Landing.tsx, frontend/src/pages/Lobby/Lobby.tsx, frontend/src/pages/Waitting/Waitting.tsx, frontend/src/routes/PrivateRoutes.tsx, frontend/src/service/socket.ts, frontend/src/setupProxy.js, frontend/src/store/room.atom.ts
- front proxy socket path 수정
- frontend socket event 로직 구현
- backend socket error fix
전체적인 서비스 사이클을 시연하는 것에 목표를 두고 frontend 로직을 구현하고
구현하는 과정에서 발생하는 백엔드 에러들을 수정하였습니다.
- close issue #81 
- 다 봐주세요
- TODO를 많이 남겨놨습니다.
- BE
- enter_user, leave_user 분리
- exception 처리 구현
- FE
- phase 타이밍
- 전체적인 고도화
- 전역 이벤트 리스너 (leave, exception)
=> client socket api 연결

.husky/pre-commit, backend/socket/package.json, backend/socket/src/constant/event.constant.ts, backend/socket/src/constant/room.constant.ts, backend/socket/src/filter/socket-exception.filter.ts, backend/socket/src/interceptor/socket-response.interceptor.ts, backend/socket/src/room/dto/socket-response.dto.ts, backend/socket/src/room/dto/webrtc.dto.ts, backend/socket/src/room/room.gateway.ts, backend/socket/src/room/service/connection/connection.service.ts, backend/socket/src/room/service/interview/interview.service.ts, backend/socket/src/room/service/webRTC/webrtc.service.ts, backend/socket/src/types/room.type.ts, backend/socket/yarn.lock, frontend/src/routes/RootRoutes.tsx
- 소켓 응답, 에러 처리 리팩토링
- webRTC 관련 socket event 로직 추가
- close issue #84 
없 음
=> 소켓 서버 리팩토링 및 webRTC 로직 추가

backend/socket/src/room/room.gateway.ts, backend/socket/src/room/room.module.ts, backend/socket/src/room/service/webRTC/webrtc.service.ts, frontend/src/hooks/useWebRTCSignaling.ts
- webRTC 로직 상 버그 수정
- FE-BE 로직 매칭
- close issue #88 
없음
없음
=> Socket webrtc 실제 테스트 후 리팩토링

backend/socket/Dockerfile, frontend/package.json
- socket Dockerfile 추가
- 프론트 lint 임시 막음
=> Hotfix/ci cd 수정

frontend/.storybook/preview.js, frontend/src/components/@shared/Button/Button.stories.tsx, frontend/src/components/@shared/Button/Button.style.ts, frontend/src/components/@shared/Button/Button.tsx
UI 통일을 위한 Button 컴포넌트를 만들었습니다.
Button 컴포넌트는 다음과 같은 속성을 가집니다.
```js
export interface buttonPropType {
children?: React.ReactNode | React.ReactNode[];
width?: string;
size?: 'small' | 'medium';
style?: 'contained' | 'text';
color?: 'primary' | 'secondary' | 'red' | 'black';
iconColor?: boolean;
disabled?: boolean;
}
```
- close issue #102 
* [frontend/src/components/@shared/Button/Button.style.ts](https://github.com/boostcampwm-2022/web14-interface/compare/102-button-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0?expand=1#diff-024626752383dfbb30bb10cac462bb70e7e4443e613100f5b3e1d42fa99f7ff3)
style 부분이 좀 더러워서 어떻게 하면 깔끔하게 적을 수 있을지 고민입니다.
없음
=> Button 컴포넌트 만들기

frontend/src/routes/RootRoutes.tsx
=> hotfix - isAuth true로 변경

frontend/src/hooks/useSafeNavigate.ts, frontend/src/hooks/useSafeNavigator.ts, frontend/src/routes/PrivateRoutes.tsx
- auth routing 로직 리팩터링
- close issue #111
=> Auth routing 로직 리팩터링

backend/socket/src/room/repository/inmemory-room.repository.ts, backend/socket/src/room/repository/interface-room.repository.ts, backend/socket/src/room/service/connection/connection.service.ts
- 모든 사용자가 나갔을 때 방 삭제
- close issue #118 
- repository에서 방과 관련된 것들을 다 삭제하고 있는데 알맞게 전부 삭제하고 있는지 확인해주세요
=> 모든 사용자가 나갔을 때 방 삭제

backend/socket/src/room/room.gateway.ts, backend/socket/src/room/service/objectstorage/objectstorage.service.ts, frontend/src/service/mediaStreamer.ts
- video stream이 잘 전달되도록 수정
- object storage에 webm 확장자 형태로 저장되도록 수정
- close issue #124 
- 동영상 upload 넘나 오래 걸림
=> 124 video stream 전달 로직 버그 수정

frontend/src/customType/dto.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/pages/Interviewee/Interviewee.tsx, frontend/src/pages/Landing/Landing.tsx, frontend/yarn.lock
- 소켓 서버 endFeedback인터페이스 수정
- 소켓 이벤트 중복 on 문제 해결
- logout 에러 해결
- close issue #146
=> endfeedback 인터페이스 변경 및 자잘한 에러 수정

frontend/src/components/@modal/EndFeedbackModal.tsx, frontend/src/components/@modal/ExitRoomModal.tsx, frontend/src/components/@modal/StartInterviewModal.tsx, frontend/src/hooks/useLeaveUser.ts, frontend/src/hooks/useWebRTCSignaling.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/pages/Interviewee/Interviewee.tsx, frontend/src/pages/Interviewer/Interviewer.tsx, frontend/src/pages/Lobby/Lobby.tsx, frontend/src/pages/Waiting/Waiting.tsx
정상작동 테스트를 위해서 170번 이슈를 같이 묶어서 해결하였습니다.
- close issue #151 
- close issue #170 
리뷰 보다는 테스트를 통해서 이벤트 리스너가 잘 제거되는지 확인 부탁드립니다.
DISCONNECT_WEBRTC는 BE 쪽에서 응답이 오지 않는 관계로 LEAVE_USER와 합쳤습니다.
CHANGE_MUTE(타인의 음소거 여부), RECEIVE_MESSAGE(채팅 수신)은 따로 이슈를 할당하여 붙이겠습니다.
=> Socket lifecycle에 따라 on/off 붙이기

frontend/src/components/BottomBar/BottomBar.style.ts, frontend/src/constants/socket.constant.ts, frontend/src/pages/Interviewee/Interviewee.style.tsx, frontend/src/pages/Interviewee/Interviewee.tsx, frontend/src/styles/theme.ts
interviewee 2차 스타일링을 진행하였습니다.
- close issue #172 
없습니다.
- #184 번 PR의 하단바를 가져와 그대로 적용하였습니다.
=> Interviewee 2차 스타일링

frontend/package.json, frontend/src/pages/Waiting/Tetris.style.css, frontend/src/pages/Waiting/Waiting.style.ts, frontend/src/pages/Waiting/Waiting.tsx, frontend/yarn.lock
싱나능 테트리승
- close issue #175 
업승
엄슴
=> React-Tetris 적용

frontend/src/components/@shared/BottomBarButton/BottomBarButton.tsx, frontend/src/components/@shared/Button/Button.style.ts, frontend/src/components/@shared/RoundButton/RoundButton.stories.tsx, frontend/src/components/@shared/RoundButton/RoundButton.style.ts, frontend/src/components/@shared/RoundButton/RoundButton.tsx, frontend/src/components/BottomBar/BottomBar.style.ts, frontend/src/components/BottomBar/BottomBar.tsx, frontend/src/pages/Lobby/Lobby.tsx
깜빡하고 커밋 안해서 추가로 올립니당.
- close issue #172 
- 관련 PR #185 
없음
없음
=> Interviewee 2차 스타일링(2)

backend/socket/src/config/pipe.config.ts, backend/socket/src/main.ts, backend/socket/src/room/dto/update-media-info.dto.ts, backend/socket/src/room/dto/user.dto.ts, backend/socket/src/room/repository/redis-room.repository.ts, backend/socket/src/room/service/connection/connection.service.ts, backend/socket/src/types/room.type.ts
- global pipe 추가
- redis room repo 메서드 추가 구현
- close issue #190
=> room repository redis 구현체

frontend/src/assets/sync_dot_line.svg, frontend/src/components/@modal/EnterRoomModal.tsx, frontend/src/components/@shared/Button/Button.style.ts, frontend/src/components/@shared/Button/Button.tsx, frontend/src/components/@shared/RoundButton/RoundButton.style.ts, frontend/src/components/@shared/RoundButton/RoundButton.tsx, frontend/src/components/@shared/VideoGrid/VideoGrid.style.ts, frontend/src/components/FeedbackEditBtns/FeedbackEditBtns.style.ts, frontend/src/components/FeedbackEditBtns/FeedbackEditBtns.tsx, frontend/src/components/FeedbackForm/FeedbackForm.style.ts, frontend/src/components/FeedbackForm/FeedbackForm.tsx, frontend/src/components/FeedbackItem/FeedbackItem.style.ts, frontend/src/components/FeedbackItem/FeedbackItem.tsx, frontend/src/components/FeedbackList/FeedbackList.style.ts, frontend/src/components/FeedbackList/FeedbackList.tsx, frontend/src/pages/Feedback/Feedback.style.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/pages/Interviewee/Interviewee.style.tsx, frontend/src/pages/Interviewee/Interviewee.tsx, frontend/src/pages/Interviewer/Interviewer.style.tsx, frontend/src/pages/Interviewer/Interviewer.tsx, frontend/src/routes/RootRoutes.tsx, frontend/src/store/auth.store.ts, frontend/src/styles/globalStyle.ts
- close issue #172 
- #174 중 스타일링 완료
피드백 페이지에서 영상 로드가 되지 않는 버그가 있습니다.
=> Interviewer & Feedback 페이지 2차 스타일링

backend/rest/src/filter/http-exception.filter.ts, backend/socket/src/constant/event.constant.ts, backend/socket/src/room/dto/chat.dto.ts, backend/socket/src/room/room.gateway.ts, backend/socket/src/room/room.module.ts, backend/socket/src/room/service/chat/chat.service.ts, backend/socket/util/rest-api.util.ts
- 소켓 서버 채팅 이벤트 구현
- rest filter 에러 처리 수정
- close issue #189
=> 소켓 서버 채팅 기능 구현

backend/socket/src/room/service/connection/connection.service.ts
- 방 삭제가 안되는 오류 수정
- 클라이언트에서 받을 user media type 수정
- close issue #198
=> 🐞 fix: (BE) - 방 삭제 및 user dto 수정

backend/rest/src/config/pipe.config.ts, backend/rest/src/filter/http-exception.filter.ts, backend/rest/src/interview/repository/typeorm-interview.repository.ts, backend/rest/src/interview/service/interview.service.ts, backend/rest/src/main.ts, backend/socket/src/config/pipe.config.ts, backend/socket/src/constant/event.constant.ts, backend/socket/src/filter/socket-exception.filter.ts, backend/socket/src/main.ts, backend/socket/src/room/dto/update-media-info.dto.ts, backend/socket/src/room/dto/user.dto.ts, backend/socket/src/room/room.gateway.ts, backend/socket/src/room/service/connection/connection.service.ts, backend/socket/src/room/service/objectstorage/objectstorage.service.ts, backend/socket/src/types/room.type.ts, yarn.lock
- object storage 영상 저장 url 수정
- docs list 조회 시 생성 순으로 ordering
- user media type 수정
- 서버 exception filter 고도화
- close issue #201
=> 백엔드 버그 수정 및 리팩토링

frontend/src/components/@modal/EndFeedbackModal.tsx, frontend/src/customType/dto.ts
FeedbackDto를 BE API에 맞게 수정
없음
없음
없음
=> hotfix / FeedbackDto 수정

backend/rest/Dockerfile, backend/socket/Dockerfile
=> Hotfix: docker file 이슈

frontend/src/hooks/useWebRTCSignaling.ts
첫 webRTC 연결 시 오디오 false로 설정
- close issue #216 
없음
없음
=> 첫 webRTC 연결 시 오디오 false로 설정

frontend/src/components/BottomBar/BottomBar.tsx, frontend/src/constants/media.constant.ts
바텀바 로비 재진입 시 아이콘 다시 false로 되는 문제 수정
- close issue #215 
없음
없음
=> 바텀바 로비 재진입 시 아이콘 다시 false로 되는 문제 수정

.github/workflows/backend-rest-deploy.yml, backend/rest/src/filter/http-exception.filter.ts
- rest server exception filter  수정
- rest server github actions script 수정
- close issue #226
=> 🚨Hotfix: rest server filter 수정 및 actions 수정

frontend/package.json, frontend/src/App.tsx, frontend/src/components/@drawer/ChatDrawer/ChatDrawer.style.ts, frontend/src/components/@drawer/ChatDrawer/ChatDrawer.tsx, frontend/src/components/@modal/InterviewDocsModal/InterviewDocsModal.tsx, frontend/src/components/InterviewDocsList/InterviewDocsList.style.ts, frontend/src/components/Loading/Loading.tsx, frontend/src/pages/Interviewer/Interviewer.style.tsx, frontend/src/pages/Landing/Landing.style.ts, frontend/src/pages/Landing/Landing.tsx, frontend/yarn.lock
- ReactLoader 라이브러리를 통한 Loading 컴포넌트 제작
- Page 이동 시 Loading 적용
- DocsModal 로딩 시 Loading 적용
- Landing 페이지 소개 문구 수정
- ChatDrawer 채팅 입력 창 구분선 추가
- close issue #169 
없습니다.
없습니다.
=> Suspense 개별화

frontend/src/components/@modal/EnterRoomModal.tsx, frontend/src/components/@shared/StreamingVideo/StreamVideo.style.ts, frontend/src/components/FeedbackList/FeedbackList.style.ts, frontend/src/pages/Feedback/Feedback.style.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/pages/Interviewee/Interviewee.style.tsx, frontend/src/pages/Interviewee/Interviewee.tsx, frontend/src/pages/Interviewer/Interviewer.tsx, frontend/src/pages/Landing/Landing.tsx, frontend/src/pages/Lobby/Lobby.style.ts, frontend/src/pages/Lobby/Lobby.tsx, frontend/src/styles/commonStyle.ts
- 피드백 페이지에 면접관 스트리밍 영상 추가
- 면접자, 면접관, 피드백 페이지 비디오 css 통일
- 스트리밍 비디오에서 글자가 길어질 경우 말줄임표 추가
- timeline 투명도 적용
- Landing 소개 페이지 소개 문구 변경
- close issue #217 
없음
없음
=> 피드백 페이지에 면접관 넣기

frontend/src/pages/Lobby/Lobby.tsx
방 입장 시에 방 생성자만 방 정보 복사 모달이 뜨도록 수정
- close issue #214 
없음
없음
=> 방 입장 시에 생성자만 복사 모달이 뜨도록 수정

frontend/src/components/RecordTimeLabel/RecordTimeLabel.style.ts, frontend/src/pages/Feedback/Feedback.tsx, frontend/src/pages/Interviewer/Interviewer.tsx
Feedback 페이지에서 비디오가 업로드 완료 전까지 로딩을 추가하였습니다.
- close issue #220 
없음
원래는 Snake 게임을 추가하려 했으나 라이브러리가 이상하여 취소하고 Loading 컴포넌트로 대체하였습니다.
=> Feedback Video Loading 추가

backend/rest/src/auth/service/auth.service.ts, backend/rest/src/common/typeorm-base.entity.ts, backend/rest/src/config/typeorm.config.ts, backend/rest/src/constant/swagger.constant.ts, backend/rest/src/filter/http-exception.filter.ts, backend/rest/src/interceptor/http.interceptor.ts, backend/rest/src/interview/controller/interview.controller.ts, backend/rest/src/interview/dto/docs.dto.ts, backend/rest/src/interview/dto/feedback.dto.ts, backend/rest/src/interview/dto/response-docs.builder.ts, backend/rest/src/interview/repository/interview.repository.ts, backend/rest/src/interview/repository/typeorm-interview.repository.ts, backend/rest/src/interview/service/interview.service.ts, backend/rest/src/types/index.ts, backend/rest/src/types/interview.type.ts, backend/rest/src/user/repository/typeorm-user.repository.ts, backend/socket/src/room/dto/chat.dto.ts
- typeORM confg 수정
- dev가 아닌 prod로 실행 시 snake_name으로 변경해주지 않아서 docs 조회 오류 였음
- chat dto 관련 validation 이슈 fix
- feedback 저장 관련 query 수정
- promise all로 실행하면 각 feedback마다 transaction 실행 됨
- bulk insert로 한 query에 모두 저장
- close issue #223
=> rest, socket 서버 버그 수정 및 rest server db 관련 리팩토링

backend/socket/src/filter/socket-exception.filter.ts, backend/socket/src/room/room.gateway.ts, backend/socket/src/room/service/connection/connection.service.ts
- 중복 회원으로 방 생성 문제 수정
- socket filter 고도화
=> 중복된 회원으로 방 생성이 안되도록 수정

backend/rest/src/common/typeorm-base.entity.ts
- base entity default 값 설정 오류 수정
=> Hotfix: base entity default 값 설정 오류 수정

frontend/craco.config.js, frontend/package.json, frontend/yarn.lock
배포 시 console.log 삭제
- transform-remove-console 설치 및 craco 설정 추가
- css loader, style loader 추가
- close issue #221 
없음
없음
=> 배포 시 console.log 삭제

frontend/src/App.tsx
Toast css가 적용되지 않는 에러를 픽스합니다.
없음
없음
없음
=> Toast Css 에러 픽스

backend/rest/src/auth/service/oauth/kakao-oauth.service.ts, backend/rest/src/filter/http-exception.filter.ts
- 카카오 OAuth 시작 시 select query가 안되던 오류 수정
- rest filter 수정
=> 카카오 oauth 관련 이슈

frontend/src/App.tsx
- Hotfix: toast library css 로드 방식 수정
=> Hotfix: toast library css 로드 방식 수정
